# Generated by Django 3.2.9 on 2021-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
